# Generated by Django 3.0.7 on 2020-09-10 08:11

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    BilledOrganization = apps.get_model("multi_tenancy", "BilledOrganization")
    BilledOrganization = apps.get_model("multi_tenancy", "BilledOrganization")
    for team_billing in BilledOrganization.objects.all():
        BilledOrganization.objects.create(
            organization=team_billing.team.organization,
            stripe_customer_id=team_billing.stripe_customer_id,
            stripe_checkout_session=team_billing.stripe_checkout_session,
            should_setup_billing=team_billing.should_setup_billing,
            billing_period_ends=team_billing.billing_period_ends,
            price_id=team_billing.price_id,
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("posthog", "0085_org_models"),
        ("multi_tenancy", "0004_auto_20200920_2021"),
    ]

    operations = [
        migrations.CreateModel(
            name="BilledOrganization",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="billing",
                        serialize=False,
                        to="posthog.Organization",
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=128)),
                (
                    "stripe_checkout_session",
                    models.CharField(blank=True, max_length=128),
                ),
                ("should_setup_billing", models.BooleanField(default=False)),
                (
                    "billing_period_ends",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("price_id", models.CharField(blank=True, default="", max_length=128)),
            ],
            bases=("posthog.organization",),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
