# Generated by Django 3.0.7 on 2020-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0004_auto_20200912_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambilling',
            name='checkout_session_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
